import type { Article } from "../types/news";

export const mockArticles: Article[] = [
  {
    id: "mock-1",
    slug: "mock-local-news-surallah",
    title: "Surallah LGU Launches New Community Health Program",
    excerpt: "The local government of Surallah has unveiled a comprehensive health initiative aimed at providing accessible medical services to remote barangays.",
    body: "<p>The local government of Surallah has unveiled a comprehensive health initiative aimed at providing accessible medical services to remote barangays across the municipality.</p><p>Mayor Antonio Bautista announced the program during Monday's flag ceremony, highlighting partnerships with the Department of Health and provincial healthcare providers.</p><p>Residents can expect regular medical missions, free check-ups, and medicine distribution starting next month.</p>",
    category: "LOCAL",
    author: { id: "author-1", name: "Radyo Bandera Surallah 98.1 FM", role: "News Desk" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    tags: ["Surallah", "Health", "LGU", "Community"],
    views: 245,
    isBreaking: false,
  },
  {
    id: "mock-2",
    slug: "mock-regional-soccsksargen",
    title: "SOCCSKSARGEN Region Reports Economic Growth in Q2",
    excerpt: "The regional economy posted a 5.8% growth in the second quarter, driven by agricultural exports and infrastructure spending.",
    body: "<p>The SOCCSKSARGEN region has posted a 5.8% economic growth in the second quarter of the year, according to the latest report from the Philippine Statistics Authority.</p><p>Key drivers include strong agricultural exports, increased infrastructure spending, and a rebound in tourism across South Cotabato, Sultan Kudarat, Sarangani, and General Santos City.</p><p>Local business groups remain optimistic about sustained growth in the coming quarters.</p>",
    category: "REGIONAL",
    author: { id: "author-1", name: "Radyo Bandera Surallah 98.1 FM", role: "News Desk" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    tags: ["SOCCSKSARGEN", "Economy", "Growth", "PSA"],
    views: 189,
    isBreaking: false,
  },
  {
    id: "mock-3",
    slug: "mock-national-philippines",
    title: "National Government Announces New Infrastructure Projects in Mindanao",
    excerpt: "The national government has approved a multi-billion peso infrastructure package targeting key road networks and bridges in Mindanao.",
    body: "<p>The national government has approved a multi-billion peso infrastructure package targeting key road networks and bridges across Mindanao, the Department of Public Works and Highways confirmed Thursday.</p><p>The projects include the completion of the Surallah-Isulan road widening, the construction of a new bridge in Tacurong City, and flood control systems in several river basins.</p><p>DPWH Secretary Manuel Bonoan said the projects are expected to create thousands of jobs and improve connectivity in the region.</p>",
    category: "NATIONAL",
    author: { id: "author-2", name: "Philippine News Agency", role: "National Correspondent" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    tags: ["Infrastructure", "Mindanao", "DPWH", "Development"],
    views: 312,
    isBreaking: false,
  },
  {
    id: "mock-4",
    slug: "mock-breaking-weather",
    title: "BREAKING: Typhoon Signal Raised in Parts of Mindanao",
    excerpt: "PAGASA raises tropical cyclone wind signal over parts of Mindanao as a low pressure area develops into a tropical depression.",
    body: "<p>The Philippine Atmospheric, Geophysical and Astronomical Services Administration (PAGASA) has raised tropical cyclone wind Signal No. 1 over several provinces in Mindanao as a low pressure area east of Davao City developed into a tropical depression.</p><p>Residents in affected areas including South Cotabato, Sultan Kudarat, and Sarangani are advised to take precautionary measures.</p><p>Local disaster risk reduction offices have been placed on alert status.</p>",
    category: "NATIONAL",
    author: { id: "author-1", name: "Radyo Bandera Surallah 98.1 FM", role: "News Desk" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    tags: ["Weather", "Typhoon", "PAGASA", "Mindanao", "Breaking"],
    views: 567,
    isBreaking: true,
  },
  {
    id: "mock-5",
    slug: "mock-local-agriculture",
    title: "Surallah Farmers Benefit from New Irrigation System",
    excerpt: "A newly completed irrigation project in Barangay Upper Bayan is expected to boost rice production for over 200 local farmers.",
    body: "<p>A newly completed irrigation project in Barangay Upper Bayan is expected to significantly boost rice production for over 200 local farmers, the Municipal Agriculture Office reported.</p><p>The system, funded through the National Irrigation Administration, covers approximately 150 hectares of agricultural land that previously relied solely on rainwater.</p><p>Farmer leaders expressed gratitude, noting that the project will allow for year-round farming and increase their average harvest from two to three cropping cycles annually.</p>",
    category: "LOCAL",
    author: { id: "author-1", name: "Radyo Bandera Surallah 98.1 FM", role: "News Desk" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    tags: ["Agriculture", "Irrigation", "Surallah", "Farmers"],
    views: 156,
    isBreaking: false,
  },
  {
    id: "mock-6",
    slug: "mock-regional-education",
    title: "DepEd SOCCSKSARGEN Launches Digital Learning Initiative",
    excerpt: "The Department of Education in SOCCSKSARGEN rolls out a new digital learning program targeting remote schools with limited resources.",
    body: "<p>The Department of Education in SOCCSKSARGEN has launched a comprehensive digital learning initiative aimed at bridging the educational gap in remote and underserved communities.</p><p>The program will deploy tablet devices pre-loaded with learning modules, establish community WiFi hotspots, and train teachers in digital pedagogy across 50 target schools in the region.</p><p>DepEd Regional Director Carlito Rocafort emphasized that the initiative is part of a broader effort to modernize education in the region.</p>",
    category: "REGIONAL",
    author: { id: "author-2", name: "Philippine News Agency", role: "National Correspondent" },
    thumbnail: "",
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    tags: ["Education", "DepEd", "Digital", "SOCCSKSARGEN"],
    views: 98,
    isBreaking: false,
  },
];
