"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _category_local from './category-local.bones.json'
import _category_national from './category-national.bones.json'
import _category_regional from './category-regional.bones.json'
import _general from './general.bones.json'
import _home from './home.bones.json'

registerBones({
  "category-local": _category_local,
  "category-national": _category_national,
  "category-regional": _category_regional,
  "general": _general,
  "home": _home,
})
